version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: heroes3
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data