"""empty message

Revision ID: fde3ef05dffb
Revises: 
Create Date: 2024-11-19 22:45:59.839457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fde3ef05dffb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opponents')
    op.drop_table('game_matches')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_title', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('videos_short_description', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('videos_short_description')
        batch_op.drop_column('video_title')

    op.create_table('game_matches',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('game_matches_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('town_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('hero_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('color_id', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='game_matches_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('opponents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('town_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('hero_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('color_id', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_match_id'], ['game_matches.id'], name='opponents_game_match_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='opponents_pkey')
    )
    # ### end Alembic commands ###
